version: '3'

services:
  image_name:
   image: image_name
   ports:
     - 4000
   environment:
     - SERVICE_PORTS=4000
   deploy:
     replicas: 3
     update_config:
       parallelism: 1
       delay: 10s
     restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
   networks:
     - web

  proxy:
    image: dockercloud/haproxy
    depends_on:
      - image_name
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
    networks:
      - web
networks:
  web:
    driver: overlay
